.github/PULL_REQUEST_TEMPLATE.md, README.md
修正 jpeg 符号和模板中 DJ 音标的链接
建议为有多种正确发音的单词建立一种格式，如果将多个正确发音塞入一个单元格，样式会不好看，比如 SQL 的正确发音有 S-Q-L 和 Sequel，以及 GUI 的正确发音有 Gee-Yu-Eye 和 Gooey
=> 修正 jpeg 符号和模板中 DJ 音标的链接

README.md
The pronunciation in the original audio resource for GNU is the same to "new",
but it should be read as /gnuː/ instead of "new"(/njuː/),  according to the article in [Wikipedia](https://en.wikipedia.org/wiki/GNU).
Really sorry for not providing a proper online audio URL from youdao, because I couldn't even find a proper online audio resource for the word GNU.
#132
=> Modified the audio resource URL for GNU

README.md
This is a very easy-to-get-wrong word for non English speaking people.
=> Add `locale`

README.md
Git 说明：原本的 [ j ] 发的是 y 的音，不会有人读成 Yit 吧
=> 	Add wrong pronunciation of Amazon; Del ridiculous pronunciation of Git

README.md
查找了Ubuntu的发音，发现原先有道的发音是不准确的，因此替换为了[wikipedia](https://upload.wikimedia.org/wikipedia/commons/b/b5/En-Ubuntu_pronunciation.oga)提供的发音，主要参考来源是以下三处：
1. [How To Pronounce "Ubuntu"](https://www.youtube.com/watch?v=8EADF3TCaK4)
2. https://www.ubuntu.com/about （上面视频中提到的官方提示）
3. https://en.wikipedia.org/wiki/Ubuntu
=> Check the pronounciation of Ubuntu on WIKI and upload its audio source

README.md
Add a link to https://github.com/b1f6c1c4/programming-pronunciations-en_US , which contains the narrow (phonetic) IPA transcription based on New York City English (NYCE).
=> sell my repo

README.md
PR说明:
1. 尽量提交常用的单词和中国程序员容易读错的单词。
1. 选择合适的Labels。
1. 音标目前为[海词](http://dict.cn/)英式发音, 使用 [DJ 音标写法](https://zh.wikipedia.org/wiki/DJ%E9%9F%B3%E6%A8%99)。
1. 音频地址 英音：http://dict.youdao.com/dictvoice?audio=${word}&type=1，美音：http://dict.youdao.com/dictvoice?audio=${word}&type=2 ，如果没有或者发音不准确再使用其他音频。
1. 音标到这个有道网页找 http://dict.youdao.com/w/eng/{word}。
1. 音标使用斜线 `/.../`。
1. tools目录下有个python程序可以从有道网站创建单词信息。
- Usage: `tools/addword.py <word>`
=> add Vagrant

README.md
1. Add `execute `and `executor `The main problem is these two words' stress are different.
2. Reorder `event `and `epoch`.
=> Add "execute" and "executor"

README.md
PR说明:
1. 尽量提交常用的单词和中国程序员容易读错的单词。
1. 选择合适的Labels。
1. 音标目前为[海词](http://dict.cn/)英式发音, 使用 [DJ 音标写法](https://zh.wikipedia.org/wiki/DJ%E9%9F%B3%E6%A8%99)。
1. 音频地址 英音：http://dict.youdao.com/dictvoice?audio=${word}&type=1，美音：http://dict.youdao.com/dictvoice?audio=${word}&type=2 ，如果没有或者发音不准确再使用其他音频。
1. 音标到这个有道网页找 http://dict.youdao.com/w/eng/{word}。
1. 音标使用斜线 `/.../`。
1. tools目录下有个python程序可以从有道网站创建单词信息。
- Usage: `tools/addword.py <word>`
=> add miscellaneous

README.md, tools/addword.py
PR说明:
1. 尽量提交常用的单词和中国程序员容易读错的单词。
1. 选择合适的Labels。
1. 音标目前为[海词](http://dict.cn/)英式发音, 使用 [DJ 音标写法](https://zh.wikipedia.org/wiki/DJ%E9%9F%B3%E6%A8%99)。
1. 音频地址 英音：http://dict.youdao.com/dictvoice?audio=${word}&type=1，美音：http://dict.youdao.com/dictvoice?audio=${word}&type=2 ，如果没有或者发音不准确再使用其他音频。
1. 音标到这个有道网页找 http://dict.youdao.com/w/eng/{word}。
1. 音标使用斜线 `/.../`。
1. tools目录下有个python程序可以从有道网站创建单词信息。
- Usage: `tools/addword.py <word>`
=> ref: 🔊 语音链接改用 https

README.md
=> 添加 谷歌浏览器 Chrome的正确发音

README.md
per https://github.com/shimohq/chinese-programmer-wrong-pronunciation/pull/65#issuecomment-736089904
=> Java: /'dʒɑːvɑː/ is not wrong

README.md
=> 增加dotnet(.net)的正确发音

README.md, tools/addword.py
1. 添加了async这个词；
2. 根据PEP8格式化addword.py，单双引号则是在不必要使用双引号的地方都统一成了单引号。
=> add word 'async' & code formatting

README.md
=> add word 'LINQ'

README.md
=> 添加 Ldap 正确发音

README.md
calendar 的美音确实是 /'kælendər/，我自己搞错了，抱歉...
=> Revert "添加 calendar 的正确读音"

README.md
你好，我基于本词库和其他词库做了一个可以自动连读的网站：https://corrector.justsong.cn/ 
自我感觉还是有点帮助的，请问可以放到「其他相关链接」中吗？
=> 添加一个可以连读的网站

README.md
```
| exit | [🔊](https://dict.youdao.com/dictvoice?audio=exit&type=1) /ˈeksɪt/ | [🔊](https://dict.youdao.com/dictvoice?audio=exit&type=2) /ˈeksɪt; ˈeɡzɪt/ | ❌ /ig'zit/ |
```
=> 为 exit 添加正确发音

README.md
=> feat: add "macro" 正确读音

README.md
=> add 'max, probe, native, telemetry' for backend development

README.md
- 修复了“GNU”的错误音标
- 将“ephemeral”的音标改成了正确的斜线格式
=> fix: corrected wrong format

README.md
=> feat:add word BIOS and UEFI

README.md, tools/chromium_extension/README.md, tools/chromium_extension/js/app/init.js
=> 解决mac系统chrome浏览器上，点击音频图标无反应；单词 ubuntu 启用https

README.md
=> feat: add word chaos (#408)

README.md
=> fix: GUI audio link

README.md
=> ephemeral 音标错误

README.md
=> feat: add word "migrate"

README.md
=> Add word `premise`

README.md
IEEE 美国电气和电子工程师协会，应该是每个程序员都绕不开的单词吧，学组成原理有 IEEE 754，学计网有 IEEE 802.3。
而且不加说明，很多人第一次一定会读错的哈。
=> feat: add new word "IEEE"

README.md
=> add résumé (resolve #439)

README.md
Add `RISC-V`. The correct pronunciation is "risk five", not "risk v".
=> Add RISC-V
