README.md

Add links to Merriam-Webster pronunciation page

---

README.md

Do you know the ducking `node_modules` ? 😄

added module.

---

README.md

yet at the same time, I do suggest that we paste the authentic/unofficial webpage as a proof to show that the modification/addition in pr/commits is trustworthy and reliable, thanks

acceptable pronunciation of retina, details view git log

---

README.md

ADD: 新增单词content,以及发音和错误示范

---

README.md

add `hover`

---

README.md

This is sometimes mistakenly pronounced  as 优帮吐.

add ubuntu

---

README.md

1. 音标以有道词典搜索结果的美式发音为主, 后续可能会增加英式发音的支持.

Add 'scheme'

---

README.md

更正 doc 的读音

---

README.md

add voice link

---

README.md

1. 音标以有道词典搜索结果的美式发音为主, 后续可能会增加英式发音的支持.

add angular

---

README.md

修改 Retina 错误发音

---

README.md

1. 音标以[海词](http://dict.cn/)的英式发音为主, 使用 [DJ 音标写法](https://zh.wikipedia.org/wiki/KK%E9%9F%B3%E6%A8%99).

Add `variable`

---

README.md

1. 音标以[海词](http://dict.cn/)的英式发音为主, 使用 [DJ 音标写法](https://zh.wikipedia.org/wiki/KK%E9%9F%B3%E6%A8%99).

Update `variable` wrong pronunciation

---

README.md

1. 音标以[海词](http://dict.cn/)的英式发音为主, 使用 [DJ 音标写法](https://zh.wikipedia.org/wiki/KK%E9%9F%B3%E6%A8%99).

feat: add 'phantom'

---

README.md

add amazon and Microsoft

---

README.md

agile  daemon

---

README.md

facade正确发音后多了一个']'

---

README.md

Reference: <https://en.wiktionary.org/wiki/digest>

Fix the accent of `digest`.

---

README.md

Add the wrong pronunciation of ASCII

---

README.md

See this link -> [What's the history of the non-official pronunciation of SQL?](https://softwareengineering.stackexchange.com/questions/8588/whats-the-history-of-the-non-official-pronunciation-of-sql)

Add alternative 'SQL' Pronunciation

---

README.md

Add Adobe 

---

README.md

Lucene is an Apache project, a Java-based indexing and search software
1. 音标以[海词](http://dict.cn/)的英式发音为主, 使用 [DJ 音标写法](https://zh.wikipedia.org/wiki/DJ%E9%9F%B3%E6%A8%99).

Add lucene

---

README.md

查找了关于GUI 的发音
原本的发音听起来很像中文发音，所以重新搜索了一下WIKI确定了其发音并且在有道上重新搜索了一下。
感谢创建此库。

Check the pronunciation of GUI on WIKI and upload its audio source

---

README.md

ADD `resume`

---

README.md

XCode segue always pronunce wrong

add 'segue'

---

README.md

1. 音标以[海词](http://dict.cn/)的英式发音为主, 使用 [DJ 音标写法](https://zh.wikipedia.org/wiki/DJ%E9%9F%B3%E6%A8%99).

add privilege pronunciation

---

README.md

1. 音标以[海词](http://dict.cn/)的英式发音为主, 使用 [DJ 音标写法](https://zh.wikipedia.org/wiki/DJ%E9%9F%B3%E6%A8%99).

add GraphQL

---

README.md

1. 音标以[海词](http://dict.cn/)的英式发音为主, 使用 [DJ 音标写法](https://zh.wikipedia.org/wiki/DJ%E9%9F%B3%E6%A8%99). √
2. 音频地址格式为 http://dict.youdao.com/dictvoice?audio=${word}&type=2, 如果没有或者发音不准确再使用其他音频. √

add 'column', 'React', 'Redux', 'route'

---

README.md

Added 'adversarial', 'C#', 'repository', 'repr', 'router', 'verbose'
PR 遵循以下条目:
1. 音标以[海词](http://dict.cn/)的英式发音为主, 使用 [DJ 音标写法](https://zh.wikipedia.org/wiki/DJ%E9%9F%B3%E6%A8%99).

Added 'adversarial' etc.

---

README.md
tools/addprons.py

This PR made the following changes. 
1. Added American English pronunciations.
2. Adjusted the table format.
3. Added the python program to add pronunciations and format the table.
To do:
- Add phonetic transcriptions for American English.
- Tweak and improve the table format.

Add American English pronunciations

---

tools/addprons.py

Add american phonetics transcription

---

tools/addword.py

Added a python program that creates the description for a word to be added to the word list
**Usage**: `addword.py <word>`

Add a program for generating the word description from youdao.com

---

.github/PULL_REQUEST_TEMPLATE.md
README.md
tools/addword.py

Everything here is IPA broad (phonemic) transcription. We should always use slashes (`/.../`) instead of brackets (`[...]`) in this case.
由于本项目采用了国际音标宽式记音，项目中所有出现的方括号（`[...]`）都应该换成斜线（`/.../`）。
References:
> https://en.wikipedia.org/wiki/International_Phonetic_Alphabet
> https://en.wikipedia.org/wiki/Phonetic_transcription#Narrow_versus_broad_transcription
> https://linguistics.stackexchange.com/questions/301/when-should-one-use-slashes-or-square-brackets-when-transcribing-in-ipa
> https://linguistics.stackexchange.com/questions/15547/should-i-use-square-brackets-or-slashes-when-transcribing-an-oral-text-in-ipa
> https://www.quora.com/What-is-the-difference-between-different-brackets-and-slashes-used-in-linguistics

replace brackets with slashes

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

Add 'Kubernetes', 'Grafana', 'gauge', 'deprecate', 'obsolete'

---

README.md

Grafana & Kubernetes pronunciation corrected

---

README.md

Add ephemeral

---

README.md

feat: add "edition" 正确读音

---

README.md

add word 'canal'

---

README.md

Add star history chart to README

---

.gitignore
tools/chromium_extension/README.md
tools/chromium_extension/js/content-script.js
tools/chromium_extension/manifest.json
tools/chromium_extension/package.json
tools/chromium_extension/rules/remove_content_security_policy.json

```shell
tools/chromium_extension
```

新增 README  页面无须跳转即可收听正确读音 的 chromium 扩展 

---

README.md

feat: add vite

---

README.md

Add legacy

---

README.md

Mark a wrong pronunciation for SQL.

"Circle" is the wrong pronunciation for SQL.

---

tools/addword.py

This PRs replaces `python3.8` with more general `python3` in `tools/addword.py` program.

Make addword.py work with all python3.* versions

---

README.md

chore: officesdk ads
